services:
  db:
    image: postgres:16-alpine
    container_name: apartmani_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: apartmani_user
      POSTGRES_PASSWORD: apartmani_pass
      POSTGRES_DB: apartmani_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apartmani_user -d apartmani_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: apartmani_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://apartmani_user:apartmani_pass@db:5432/apartmani_db"
      JWT_SECRET: "brF5b1eM8MHxPZfpYzbpVRM1K9mUT5zX/QTiPBKNOx4="
      PORT: "3000"
      FRONTEND_URL: "http://localhost:8080"
      NODE_ENV: "production"
      STRIPE_SECRET_KEY: "sk_test_51TkhOvRyG7RlIecMCnNoc8xsDVoQwk33RPOO4l2BstryOwb82krOtauMWDM4Qs2CcFGffiea2cJnyV4nvUQX3Mvc00t8CIhBx6"
      STRIPE_WEBHOOK_SECRET: "whsec_35af9830ea948f30c232cf629cee5e7e1d532f938a475e423fd4a05ab7806592"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3000"
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "/api"
    container_name: apartmani_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  postgres_data:
